db = db.getSiblingDB('PruebaTecnicaNebulae');

db.usuario.insertMany([
  {
    numInterno: 254152,
    nombre: 'Yeimer Jaramillo',
    email: 'yeimer@mail.com',
    rol: 'admin',
    activo: true,
  },
  {
    numInterno: 45124,
    nombre: 'Andres Fernandez',
    email: 'andresFernandez@gmail.com',
    rol: 'cliente',
    activo: true,
  },
]);

db.producto.insertMany([
  {
    nombre: 'Mochila Escolar',
    precio: 2004.98,
    stock: 23,
    activo: true,
    categoria: 'Otros',
  },
  {
    nombre: 'Medias de Algodón',
    precio: 835.06,
    stock: 23,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Chaqueta Impermeable',
    precio: 59.03,
    stock: 6,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Toalla de Baño',
    precio: 2423.0,
    stock: 30,
    activo: true,
    categoria: 'Hogar',
  },
  {
    nombre: 'Mochila Escolar',
    precio: 404.87,
    stock: 11,
    activo: false,
    categoria: 'Otros',
  },
  {
    nombre: 'Juego de Herramientas',
    precio: 1898.76,
    stock: 1,
    activo: true,
    categoria: 'Otros',
  },
  {
    nombre: 'Celular Android',
    precio: 483.36,
    stock: 22,
    activo: true,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Vestido de Fiesta',
    precio: 1786.84,
    stock: 1,
    activo: false,
    categoria: 'Ropa',
  },
  {
    nombre: 'Cargador USB-C',
    precio: 2047.37,
    stock: 15,
    activo: true,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Almohada Ortopédica',
    precio: 666.56,
    stock: 23,
    activo: false,
    categoria: 'Otros',
  },
  {
    nombre: 'Almohada Ortopédica',
    precio: 363.45,
    stock: 21,
    activo: false,
    categoria: 'Otros',
  },
  {
    nombre: 'Chaqueta Impermeable',
    precio: 859.06,
    stock: 24,
    activo: false,
    categoria: 'Ropa',
  },
  {
    nombre: 'Zapatos de Cuero',
    precio: 1243.88,
    stock: 9,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Cortina Blackout',
    precio: 620.37,
    stock: 15,
    activo: true,
    categoria: 'Hogar',
  },
  {
    nombre: 'Power Bank 20000mAh',
    precio: 1947.83,
    stock: 8,
    activo: true,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Pantalón Jeans',
    precio: 710.63,
    stock: 26,
    activo: false,
    categoria: 'Ropa',
  },
  {
    nombre: 'Chaqueta Impermeable',
    precio: 1514.91,
    stock: 5,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Cargador USB-C',
    precio: 1236.85,
    stock: 19,
    activo: false,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Pantalón Jeans',
    precio: 1726.19,
    stock: 29,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Jabón Líquido',
    precio: 1946.28,
    stock: 15,
    activo: true,
    categoria: 'Hogar',
  },
  {
    nombre: 'Microondas Digital',
    precio: 319.97,
    stock: 9,
    activo: true,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Mochila Escolar',
    precio: 1926.69,
    stock: 18,
    activo: true,
    categoria: 'Otros',
  },
  {
    nombre: 'Teclado Mecánico',
    precio: 131.99,
    stock: 23,
    activo: true,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Lavadora 20kg',
    precio: 284.2,
    stock: 21,
    activo: true,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Vestido de Fiesta',
    precio: 58.64,
    stock: 24,
    activo: false,
    categoria: 'Ropa',
  },
  {
    nombre: 'Mochila Escolar',
    precio: 921.91,
    stock: 17,
    activo: false,
    categoria: 'Otros',
  },
  {
    nombre: 'Medias de Algodón',
    precio: 690.86,
    stock: 25,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Sombrilla Plegable',
    precio: 14.61,
    stock: 27,
    activo: true,
    categoria: 'Otros',
  },
  {
    nombre: 'Juego de Herramientas',
    precio: 2301.62,
    stock: 14,
    activo: true,
    categoria: 'Otros',
  },
  {
    nombre: 'Chaqueta Impermeable',
    precio: 2204.7,
    stock: 16,
    activo: false,
    categoria: 'Ropa',
  },
  {
    nombre: 'Toalla de Baño',
    precio: 1721.18,
    stock: 28,
    activo: false,
    categoria: 'Hogar',
  },
  {
    nombre: 'Cafetera Eléctrica',
    precio: 1447.14,
    stock: 3,
    activo: true,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Almohada Ortopédica',
    precio: 2283.43,
    stock: 6,
    activo: true,
    categoria: 'Otros',
  },
  {
    nombre: 'Lavadora 20kg',
    precio: 2125.37,
    stock: 13,
    activo: false,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Almohada Ortopédica',
    precio: 878.53,
    stock: 6,
    activo: false,
    categoria: 'Otros',
  },
  {
    nombre: 'Juego de Herramientas',
    precio: 1075.16,
    stock: 17,
    activo: false,
    categoria: 'Otros',
  },
  {
    nombre: 'Cortina Blackout',
    precio: 2021.36,
    stock: 9,
    activo: false,
    categoria: 'Hogar',
  },
  {
    nombre: 'Pulsera Inteligente',
    precio: 1609.59,
    stock: 5,
    activo: false,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Tablet 10 pulgadas',
    precio: 412.45,
    stock: 23,
    activo: false,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Sábana Doble',
    precio: 1778.16,
    stock: 5,
    activo: true,
    categoria: 'Hogar',
  },
  {
    nombre: 'Almohada Ortopédica',
    precio: 2075.17,
    stock: 13,
    activo: false,
    categoria: 'Otros',
  },
  {
    nombre: 'Pulsera Inteligente',
    precio: 1233.1,
    stock: 29,
    activo: true,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Zapatos de Cuero',
    precio: 303.51,
    stock: 22,
    activo: false,
    categoria: 'Ropa',
  },
  {
    nombre: 'Teclado Mecánico',
    precio: 820.19,
    stock: 27,
    activo: false,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Celular Android',
    precio: 649.67,
    stock: 3,
    activo: false,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Zapatos de Cuero',
    precio: 1360.48,
    stock: 3,
    activo: false,
    categoria: 'Ropa',
  },
  {
    nombre: 'Audífonos Bluetooth',
    precio: 621.28,
    stock: 3,
    activo: false,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Tablet 10 pulgadas',
    precio: 1143.68,
    stock: 26,
    activo: true,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Jabón Líquido',
    precio: 937.12,
    stock: 4,
    activo: false,
    categoria: 'Hogar',
  },
  {
    nombre: 'Zapatos de Cuero',
    precio: 1858.99,
    stock: 3,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Espejo de Baño',
    precio: 1629.98,
    stock: 12,
    activo: true,
    categoria: 'Hogar',
  },
  {
    nombre: 'Toalla de Baño',
    precio: 880.99,
    stock: 11,
    activo: true,
    categoria: 'Hogar',
  },
  {
    nombre: 'Pulsera Inteligente',
    precio: 60.16,
    stock: 3,
    activo: false,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Freidora de Aire',
    precio: 1157.32,
    stock: 1,
    activo: false,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Camiseta Deportiva',
    precio: 733.4,
    stock: 25,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Chaqueta Impermeable',
    precio: 451.69,
    stock: 18,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Freidora de Aire',
    precio: 2379.77,
    stock: 26,
    activo: true,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Pelota Antiestrés',
    precio: 1616.55,
    stock: 13,
    activo: false,
    categoria: 'Otros',
  },
  {
    nombre: 'Juego de Herramientas',
    precio: 1685.19,
    stock: 27,
    activo: false,
    categoria: 'Otros',
  },
  {
    nombre: 'Camiseta Deportiva',
    precio: 1509.26,
    stock: 20,
    activo: false,
    categoria: 'Ropa',
  },
  {
    nombre: 'Vestido de Fiesta',
    precio: 1956.98,
    stock: 7,
    activo: false,
    categoria: 'Ropa',
  },
  {
    nombre: 'Camiseta Deportiva',
    precio: 2279.55,
    stock: 1,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Cafetera Eléctrica',
    precio: 1956.84,
    stock: 5,
    activo: true,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Teclado Mecánico',
    precio: 2040.21,
    stock: 9,
    activo: false,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Plancha a Vapor',
    precio: 2136.38,
    stock: 9,
    activo: true,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Power Bank 20000mAh',
    precio: 1624.31,
    stock: 3,
    activo: false,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Lavadora 20kg',
    precio: 1908.46,
    stock: 23,
    activo: false,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Vestido de Fiesta',
    precio: 293.01,
    stock: 1,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Audífonos Bluetooth',
    precio: 2012.14,
    stock: 22,
    activo: true,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Juego de Herramientas',
    precio: 1623.72,
    stock: 1,
    activo: true,
    categoria: 'Otros',
  },
  {
    nombre: 'Camiseta Deportiva',
    precio: 797.79,
    stock: 4,
    activo: false,
    categoria: 'Ropa',
  },
  {
    nombre: 'Zapatos de Cuero',
    precio: 42.05,
    stock: 21,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Camiseta Deportiva',
    precio: 1357.61,
    stock: 3,
    activo: false,
    categoria: 'Ropa',
  },
  {
    nombre: 'Audífonos Bluetooth',
    precio: 486.95,
    stock: 26,
    activo: true,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Televisor 50 pulgadas',
    precio: 1963.78,
    stock: 22,
    activo: false,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Cafetera Eléctrica',
    precio: 2438.77,
    stock: 21,
    activo: false,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Aspiradora Robot',
    precio: 60.35,
    stock: 13,
    activo: true,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Jabón Líquido',
    precio: 1153.8,
    stock: 24,
    activo: true,
    categoria: 'Hogar',
  },
  {
    nombre: 'Lavadora 20kg',
    precio: 2208.14,
    stock: 30,
    activo: false,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Almohada Ortopédica',
    precio: 1699.61,
    stock: 21,
    activo: false,
    categoria: 'Otros',
  },
  {
    nombre: 'Sábana Doble',
    precio: 1503.21,
    stock: 28,
    activo: true,
    categoria: 'Hogar',
  },
  {
    nombre: 'Almohada Ortopédica',
    precio: 890.29,
    stock: 8,
    activo: false,
    categoria: 'Otros',
  },
  {
    nombre: 'Toalla de Baño',
    precio: 1304.91,
    stock: 9,
    activo: true,
    categoria: 'Hogar',
  },
  {
    nombre: 'Espejo de Baño',
    precio: 2270.25,
    stock: 7,
    activo: false,
    categoria: 'Hogar',
  },
  {
    nombre: 'Tablet 10 pulgadas',
    precio: 1817.64,
    stock: 7,
    activo: false,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Lavadora 20kg',
    precio: 1847.37,
    stock: 6,
    activo: true,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Toalla de Baño',
    precio: 1786.26,
    stock: 5,
    activo: false,
    categoria: 'Hogar',
  },
  {
    nombre: 'Toalla de Baño',
    precio: 1356.42,
    stock: 24,
    activo: false,
    categoria: 'Hogar',
  },
  {
    nombre: 'Freidora de Aire',
    precio: 625.21,
    stock: 22,
    activo: false,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Pelota Antiestrés',
    precio: 1778.19,
    stock: 21,
    activo: false,
    categoria: 'Otros',
  },
  {
    nombre: 'Refrigerador No Frost',
    precio: 1322.43,
    stock: 29,
    activo: true,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Lámpara LED',
    precio: 2033.55,
    stock: 19,
    activo: true,
    categoria: 'Hogar',
  },
  {
    nombre: 'Teclado Mecánico',
    precio: 453.18,
    stock: 11,
    activo: true,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Refrigerador No Frost',
    precio: 2030.36,
    stock: 10,
    activo: false,
    categoria: 'Electrodomésticos',
  },
  {
    nombre: 'Espejo de Baño',
    precio: 2480.84,
    stock: 25,
    activo: true,
    categoria: 'Hogar',
  },
  {
    nombre: 'Sábana Doble',
    precio: 970.3,
    stock: 30,
    activo: false,
    categoria: 'Hogar',
  },
  {
    nombre: 'Pantalón Jeans',
    precio: 862.08,
    stock: 1,
    activo: true,
    categoria: 'Ropa',
  },
  {
    nombre: 'Mochila Escolar',
    precio: 2120.15,
    stock: 26,
    activo: true,
    categoria: 'Otros',
  },
  {
    nombre: 'Juego de Herramientas',
    precio: 1869.88,
    stock: 29,
    activo: true,
    categoria: 'Otros',
  },
  {
    nombre: 'Televisor 50 pulgadas',
    precio: 696.85,
    stock: 14,
    activo: true,
    categoria: 'Tecnología',
  },
]);
